"""Add repr and CheckConstraint

Revision ID: 550b6442c8cc
Revises: 9512f92578e9
Create Date: 2024-08-11 00:44:42.540565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550b6442c8cc'
down_revision = '9512f92578e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
